pipelines:
  default:
    - parallel:
      - step:
          name: Code lint check
          image: camdl/node-xslt-nailgun-pipelines:1.0.0-node-8-jre-8
          caches:
            - node
          script:
            - npm ci
            - npm run lint
      - step:
          name: Compile & test XSLT Nailgun server; build npm package
          image: camdl/node-xslt-nailgun-pipelines:1.1.1-node-8-jdk-8
          caches:
            - maven
            - node
          script:
            - make all
          artifacts:
            - java/target/jars/*.jar
            - build/lib.cam-xslt-nailgun-*.tgz
    - parallel:
      - step:
          name: Unit test Node 8, Java 8
          image: camdl/node-xslt-nailgun-pipelines:1.0.0-node-8-jre-8
          caches:
            - node
          script:
            - npm ci
            - npm run test
      - step:
          name: Unit test Node 12, Java 13
          image: camdl/node-xslt-nailgun-pipelines:1.0.0-node-12-jre-13
          caches:
            - node
          script:
            - npm ci
            - npm run test
      - step:
          name: Integration test Node 8, Java 8
          image: camdl/node-xslt-nailgun-pipelines:1.0.0-node-8-jre-8
          caches:
            - node
          script:
            - examples/run-all.sh
      - step:
          name: Integration test Node 12, Java 13
          image: camdl/node-xslt-nailgun-pipelines:1.0.0-node-12-jre-13
          caches:
            - node
          script:
            - examples/run-all.sh
