version: '3'

services:
  build-package:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: packager
      args:
        NODE_VERSION: v12
        JAVA_VERSION_SHORT: 11
    working_dir: /code
    volumes:
      - .:/code
      - /code/node_modules
      - java-build:/code/java/target
      - node-build:/code/build
      - maven-repository-cache:/root/.m2/repository
    command: make

  test_node-oldest_java-oldest:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: test-runner
      args:
        NODE_VERSION: v12
        JAVA_VERSION_SHORT: 11
    volumes:
      - .:/project-files:ro
      - java-build:/code/java/target:ro
      - node-build:/code/build:ro
  integration-test_node-oldest_java-oldest:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: integration-test-runner
      args:
        NODE_VERSION: v12
        JAVA_VERSION_SHORT: 11
    volumes:
      - .:/project-files:ro
      - java-build:/code/java/target:ro
      - node-build:/code/build:ro

  test_node-latest_java-latest:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: test-runner
      args:
        NODE_VERSION: v17
        JAVA_VERSION_SHORT: 17
    volumes:
      - .:/project-files:ro
      - java-build:/code/java/target:ro
      - node-build:/code/build:ro
  integration-test_node-latest_java-latest:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: integration-test-runner
      args:
        NODE_VERSION: v17
        JAVA_VERSION_SHORT: 17
    volumes:
      - .:/project-files:ro
      - java-build:/code/java/target:ro
      - node-build:/code/build:ro

volumes:
  java-build:
  node-build:
  maven-repository-cache:
