name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - run: make
      - uses: actions/upload-artifact@v2
        with:
          name: jars
          path: java/target/jars/
      - uses: actions/upload-artifact@v2
          with:
            name: npm-package
            path: build/lib.cam-xslt-nailgun-*.tgz
  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        java-version: [11, 15]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up JRE ${{ matrix.node-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.node-version }}
          java-package: jre
      - name: Download jars from build
        uses: actions/download-artifact@v2
        with:
          name: jars
          path: java/target/jars/
      - run: npm ci
      - run: npm test

  integration_test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x ]
        java-version: [ 11, 15 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up JRE ${{ matrix.node-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.node-version }}
          java-package: jre
      - name: Download npm-package from build
          uses: actions/download-artifact@v2
          with:
            name: npm-package
            path: dist/
      - run: integration-test/run-all.sh
      - run: examples/run-all.sh
